language: java
jdk:
  - openjdk11
sudo: required
services:
  - docker

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
    - '$HOME/src/main/resources/static/node_modules'
before_script:
  - chmod +x gradlew
# clean 후 Build (Build시 자동으로 test 수행)
script:
  - ./gradlew clean build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - mgh3326@naver.com.com