spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    open-in-view: false
  mvc:
    hiddenmethod:
      filter:
        # HTML <FORM>에서 th:method에서 PUT 또는 DELETE를 사용해서 보내는 _method를 사용해서  @PutMapping과 @DeleteMapping으로 요청을 맵핑.
        enabled: true
logging:
  level:
    org.hibernate.SQL: debug

# 톰캣 기본 요청 사이즈는 2MB 입니다. 그것보다 큰 요청을 받고 싶은 경우에 이 값을 조정해야 합니다.
server:
  tomcat:
    max-http-form-post-size: 5MB
  # 웹 서버 호스트
  app:
    host: http://localhost:8080

